// ⚡ ملف البراند — غير الملف ده لكل عميل جديد
export const BRAND_CONFIG = {
  name: "بصلة مصر",
  nameEn: "Basla Egypt",
  tagline: "كشري بصلة.... لأنك تستحق",
  logo: "/Images/BaslaLogo.jpg",
  primaryColor: "#F5890A",
  primaryDark: "#C96D00",
  accentColor: "#1A1A1A",
  bgColor: "#111111",
  textColor: "#FFFFFF",
  currency: "جنيه",
  currencyCode: "EGP",
  phone: "17752",
  phones: ["01044922068", "01107559113"],
  whatsapp: "01201722229",
  address: "مصر",
  socialLinks: {
    facebook: "https://www.facebook.com/profile.php?id=61581506462322",
    instagram: "",
    whatsapp: "01201722229",
  },
  googleSheetApiUrl: "https://script.google.com/macros/s/AKfycbzYVynhVXSwOiQmLZFFC6mqZcg6GJKJic2HztRmJmmSJ57nCbAJwbZBE-E3njE2-swY/exec",
  defaultTheme: "dark",
  adminPassword: "basla123",
};

// ========================
// Slider Images (صور السلايدر)
// ========================
export const SLIDER_IMAGES = [
  {
    src: "/Images/672688994_122127123633050215_6655007981988485268_n.jpg",
    alt: "كشري بصلة",
    caption: "كشري بصلة.... لأنك تستحق",
    sub: "أكلة مصرية أصيلة بأيدي محترفة",
  },
  {
    src: "/Images/706477052_122130120453050215_8515994582264094129_n.jpg",
    alt: "طواجن بصلة",
    caption: "طواجن بصلة",
    sub: "طعم البيت في كل لقمة",
  },
  {
    src: "/Images/690574064_122128559133050215_2724818770922357598_n.jpg",
    alt: "وجبات بصلة",
    caption: "وجبات متكاملة",
    sub: "كل الأذواق في مكان واحد",
  },
  {
    src: "/Images/708700887_122130519231050215_8390209153081266837_n.jpg",
    alt: "مكونات طازجة",
    caption: "مكونات طازجة يومياً",
    sub: "نضمن لك الجودة والنكهة",
  },
  {
    src: "/Images/702637444_122129861583050215_2024559277383344822_n.jpg",
    alt: "تشكيلة متنوعة",
    caption: "تشكيلة واسعة",
    sub: "من الكشري للكريب والشاورما",
  },
  {
    src: "/Images/712269033_122130889827050215_3135680032512992590_n.jpg",
    alt: "فراخ مشوية",
    caption: "فراخ شواية طازجة",
    sub: "مشوية على الجمر بيد الخبراء",
  },
  {
    src: "/Images/716611273_923847177364828_166596235557199974_n.jfif",
    alt: "بصلة مصر",
    caption: "بصلة مصر — منذ سنوات",
    sub: "تاريخ طويل من الشهرة والثقة",
  },
];

// ========================
// Offers / Deals (العروض)
// ========================
export const OFFERS_DATA = [
  {
    id: "offer1",
    badgeText: "عرض اليوم",
    badgeIcon: "Flame",
    title: "كشري بصلة التاريخي",
    desc: "أشهر كشري في مصر — تاريخ من قبل ما تتذكر!",
    image: "/Images/571216631_122106749745050215_8304593712447940953_n.jpg",
    highlight: "بداية من 15 جنيه",
    color: "#F5890A",
  },
  {
    id: "offer2",
    badgeText: "الأكثر طلباً",
    badgeIcon: "Star",
    title: "كومبو الطاجن",
    desc: "طاجن لحمة أو فراخ + كانز + بطاطس بسعر خاص",
    image: "/Images/575176081_122108015529050215_4650941299580560784_n.jpg",
    highlight: "من 60 جنيه بس",
    color: "#E05A00",
  },
  {
    id: "offer3",
    badgeText: "عائلي",
    badgeIcon: "Users",
    title: "وجبة شاورما عائلية",
    desc: "شاورما عربي عائلية تكفي الكل بسعر مميز",
    image: "/Images/612889375_122116740519050215_5217751964211567857_n.jpg",
    highlight: "260 جنيه فقط",
    color: "#D4400A",
  },
];

export const MENU_DATA = {
  categories: [
    {
      id: "koshary",
      name: "الكشري",
      icon: "bowl-food",
      color: "#F5890A",
      items: [
        { id: "k1", name: "علبة صغيرة", price: 15, description: "" },
        { id: "k2", name: "علبة لارج", price: 20, description: "" },
        { id: "k3", name: "علبة بصلة", price: 25, description: "" },
        { id: "k4", name: "علبة جامبو", price: 30, description: "" },
        { id: "k5", name: "علبة عائلي", price: 40, description: "" },
        { id: "k6", name: "جامبو عائلي", price: 50, description: "" },
      ],
    },
    {
      id: "sweets",
      name: "حلو بصلة",
      icon: "cake",
      color: "#E8A020",
      items: [
        { id: "s1", name: "أرز باللبن ساده", price: 15, description: "" },
        { id: "s2", name: "أرز باللبن ساده كبير", price: 20, description: "" },
        { id: "s3", name: "أرز باللبن مكسرات", price: 25, description: "" },
        { id: "s4", name: "أرز باللبن بسبوسه", price: 25, description: "" },
        { id: "s5", name: "أرز باللبن باللوتس", price: 25, description: "" },
        { id: "s6", name: "أرز باللبن فرن", price: 20, description: "" },
        { id: "s7", name: "كريم كراميل", price: 25, description: "" },
        { id: "s8", name: "جيلي ساده", price: 20, description: "" },
        { id: "s9", name: "مهلبية", price: 20, description: "" },
        { id: "s10", name: "مهلبية فرن", price: 25, description: "" },
      ],
    },
    {
      id: "extras",
      name: "إضافات بصلة",
      icon: "plus-circle",
      color: "#D4891A",
      items: [
        { id: "e1", name: "إضافة بطاطس", price: 25, priceRange: "20-30", description: "" },
        { id: "e2", name: "إضافة موتزريلا", price: 20, priceRange: "15-25", description: "" },
        { id: "e3", name: "تقلية - عدس - حمص", price: 8, description: "" },
        { id: "e4", name: "سلطه خيار+توست", price: 8, description: "" },
        { id: "e5", name: "طماطم متبلة+شطة زيت", price: 6, description: "" },
        { id: "e6", name: "اضافه موتزريلا", price: 25, description: "" },
        { id: "e7", name: "از بسمتي", price: 25, priceRange: "20-30", description: "" },
        { id: "e8", name: "تومية", price: 10, description: "" },
        { id: "e9", name: "مخلل", price: 10, description: "" },
        { id: "e10", name: "معمره", price: 15, description: "" },
        { id: "e11", name: "عيش سوري", price: 5, description: "" },
      ],
    },
    {
      id: "tajeen",
      name: "طواجن بصلة",
      icon: "flame",
      color: "#E05A00",
      items: [
        { id: "t1", name: "طاجن لحمة", price: 35, description: "" },
        { id: "t2", name: "طاجن فراخ", price: 45, description: "" },
        { id: "t3", name: "طاجن لحمة موتزاريلا", price: 55, description: "" },
        { id: "t4", name: "طاجن فراخ موتزاريلا", price: 65, description: "" },
        { id: "t5", name: "ميكس طاجن لحمة", price: 55, description: "" },
        { id: "t6", name: "ميكس طاجن فراخ", price: 65, description: "" },
      ],
    },
    {
      id: "crepe-chicken",
      name: "كريب فراخ",
      icon: "utensils",
      color: "#F5890A",
      items: [
        { id: "cf1", name: "كريب بانيه", price: 60, priceRange: "50-70", description: "" },
        { id: "cf2", name: "كريب كرانشي", price: 70, priceRange: "60-80", description: "" },
        { id: "cf3", name: "كريب شيش", price: 70, priceRange: "60-80", description: "" },
        { id: "cf4", name: "كريب استربس", price: 70, priceRange: "60-80", description: "" },
        { id: "cf5", name: "كريب شاورما فراخ", price: 80, priceRange: "70-90", description: "" },
        { id: "cf6", name: "كريب ميكس فراخ", price: 80, priceRange: "70-90", description: "" },
        { id: "cf7", name: "كريب فاهيتا", price: 70, priceRange: "60-80", description: "" },
        { id: "cf8", name: "كريب بصلة جامبو", price: 90, description: "" },
      ],
    },
    {
      id: "crepe-meat",
      name: "كريب لحوم",
      icon: "beef",
      color: "#C85000",
      items: [
        { id: "cm1", name: "كريب برجر", price: 60, priceRange: "50-70", description: "" },
        { id: "cm2", name: "كريب كفتة", price: 55, priceRange: "45-65", description: "" },
        { id: "cm3", name: "كريب سوسيس", price: 55, priceRange: "45-65", description: "" },
        { id: "cm4", name: "كريب مشكل لحوم", price: 70, priceRange: "60-80", description: "" },
        { id: "cm5", name: "كريب سوبريم", price: 70, priceRange: "60-80", description: "" },
        { id: "cm6", name: "كريب سجق", price: 60, priceRange: "50-70", description: "" },
        { id: "cm7", name: "كريب ميلانو", price: 70, priceRange: "60-80", description: "" },
        { id: "cm8", name: "كريب بطاطس", price: 45, priceRange: "40-50", description: "" },
        { id: "cm9", name: "كريب رومي", price: 45, priceRange: "40-50", description: "" },
        { id: "cm10", name: "كريب شيدر", price: 45, priceRange: "40-50", description: "" },
        { id: "cm11", name: "كريب مشكل جبن", price: 45, priceRange: "40-50", description: "" },
        { id: "cm12", name: "كريب جبن و خضار", price: 45, priceRange: "40-50", description: "" },
      ],
    },
    {
      id: "crepe-sweet",
      name: "كريب حلو",
      icon: "candy",
      color: "#E8A020",
      items: [
        { id: "cs1", name: "كريب نوتيلا", price: 40, description: "" },
        { id: "cs2", name: "كريب مكسرات", price: 35, description: "" },
        { id: "cs3", name: "كريب موز", price: 35, description: "" },
      ],
    },
    {
      id: "shawarma",
      name: "قسم الشاورما",
      icon: "sandwich",
      color: "#D4400A",
      items: [
        { id: "sh1", name: "شاورما فراخ", price: 60, priceRange: "50-70", description: "" },
        { id: "sh2", name: "وجبة شاورما عربي", price: 80, description: "" },
        { id: "sh3", name: "وجبة شاورما عربي دوبل", price: 150, description: "" },
        { id: "sh4", name: "وجبة شاورما عربي اكسترا", price: 100, description: "" },
        { id: "sh5", name: "فتة شاورما وسط", price: 88, priceRange: "75-100", description: "" },
        { id: "sh6", name: "فتة كريسبي", price: 88, priceRange: "80-95", description: "" },
        { id: "sh7", name: "وجبة شيش طاووق", price: 100, priceRange: "90-110", description: "" },
        { id: "sh8", name: "وجبة بانية فرش", price: 88, priceRange: "80-95", description: "" },
        { id: "sh9", name: "وجبة كرسبي فرش", price: 100, priceRange: "90-110", description: "" },
        { id: "sh10", name: "وجبة شاورما عربي عائلية", price: 260, description: "" },
      ],
    },
    {
      id: "chicken",
      name: "قسم الفراخ",
      icon: "drumstick",
      color: "#E05A00",
      items: [
        { id: "ch1", name: "فرخة شواية", price: 300, description: "" },
        { id: "ch2", name: "½ فرخة شواية", price: 160, description: "" },
        { id: "ch3", name: "¼ فرخة شواية صدر", price: 90, description: "" },
        { id: "ch4", name: "¼ فرخة شواية ورك", price: 80, description: "" },
        { id: "ch5", name: "وجبة دبل وراك مشوية", price: 210, description: "" },
        { id: "ch6", name: "فرخة شواية سادة", price: 275, description: "" },
        { id: "ch7", name: "½ فرخة شواية سادة", price: 140, description: "" },
      ],
    },
    {
      id: "syrian",
      name: "قسم السوري",
      icon: "pizza",
      color: "#C85000",
      items: [
        { id: "sy1", name: "بطاطس سوري", price: 20, priceRange: "15-20-25", description: "" },
        { id: "sy2", name: "بطاطس جبنة", price: 25, priceRange: "20-30", description: "" },
        { id: "sy3", name: "بانية علي بطاطس", price: 25, priceRange: "20-30", description: "" },
        { id: "sy4", name: "بانية فريش", price: 48, priceRange: "40-55", description: "" },
        { id: "sy5", name: "كرسبي فريش", price: 58, priceRange: "50-65", description: "" },
        { id: "sy6", name: "زنجر", price: 50, priceRange: "45-55", description: "" },
        { id: "sy7", name: "شيش طاووك", price: 60, priceRange: "50-70", description: "" },
        { id: "sy8", name: "هوت دوج", price: 30, priceRange: "25-35", description: "" },
        { id: "sy9", name: "برجر", price: 40, priceRange: "35-45", description: "" },
        { id: "sy10", name: "فاهيتا", price: 63, priceRange: "55-70", description: "" },
      ],
    },
    {
      id: "combos",
      name: "وجبات الكومبو",
      icon: "package",
      color: "#F5890A",
      items: [
        { id: "co1", name: "طاجن لحمة+كانز+بطاطس", price: 60, description: "بدلاً من 70" },
        { id: "co2", name: "طاجن فراخ+كانز+بطاطس", price: 75, description: "بدلاً من 85" },
      ],
    },
  ],
};
